datamodule:
  dataset:
    dataset_cls: LogoMultilabelDataset
    data_path: /home/ubuntu/datasets/LOGO/Logo_clf
    label_path: /home/ubuntu/datasets/LOGO/Logo_clf/meta_mlclf.csv
    augmentations: null
    transforms:
      - transforms.Resize((416, 416))
      - transforms.ToTensor()
      - transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    num_classes: 392
    random_split: False
  dataloader:
    num_workers: 8
    batch_size: 16
    shuffle: True
    drop_last: False
  
lightning_module:
  prob: sigmoid
  model: 
    name: efficientnet_b5_pretrained
    kwargs:
      num_classes: 392
    ckpt: /home/ubuntu/yha/LogoProject/logo_clf/ckpt/2022-01-21_15:21:02/efficientnet_b5_pretrained-epoch=007--valid_precision_epoch=0.7454.ckpt
  loss:
    name: torch.nn.BCEWithLogitsLoss
    kwargs: {}
  evaluation:
    items:
      - {name: Precision, kwargs: {k: 5, threshold: 0.5, name: precision}}
      - {name: Recall, kwargs: {k: 5, threshold: 0.5, name: recall}}
      - {name: F1, kwargs: {k: 5, threshold: 0.5, name: f1}}

  optimizer: 
    name: AdamW
    kwargs: 
      lr: 0.00005    
  scheduler: 
    name: CosineAnnealingLR
    kwargs:
      T_max: 10

trainer:
  gpus: [0]
  min_epochs: 1
  max_epochs: 10
  num_processes: 1
  auto_select_gpus: False
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: False
  accumulate_grad_batches: 1
  precision: 16
  weights_summary: top
  auto_lr_find: False
  auto_scale_batch_size: False
  move_metrics_to_cpu: False
  wandb_logger:
    project: Logo_vienna_code_classification
    name: test_eb5_mlclf_best_s

callback:
  callback_cls: LogoMultilabelCallback
  num_samples: 16
  data_path: /home/ubuntu/datasets/LOGO/Logo_clf
  label_path: /home/ubuntu/datasets/LOGO/Logo_clf/meta_mlclf.csv
  label_col: label