datamodule:
  dataset:
    dataset_cls: LogoDataset
    data_path: /home/ubuntu/datasets/LOGO/Logo_clf
    label_path: /home/ubuntu/datasets/LOGO/Logo_clf/meta.csv
    augmentations: null
    transforms:
      - transforms.Resize((416, 416))
      - transforms.RandomGrayscale(p=0.2)
      - transforms.ToTensor()
      - transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    num_classes: 392
    random_split: False
  dataloader:
    num_workers: 4
    batch_size: 8
    shuffle: True
    drop_last: False
  
lightning_module:
  prob: sigmoid
  model: 
    name: efficientnet_b5_pretrained
    kwargs:
      num_classes: 392
    ckpt: /home/ubuntu/yha/LogoProject/logo_clf/ckpt/efficientnet_b5_pretrained-epoch=006--valid_precision_epoch=0.7432.ckpt
  loss:
    name: torch.nn.CrossEntropyLoss
    kwargs: {}
  evaluation:
    items:
      - {name: torchmetrics.Accuracy, kwargs: {}}
      - {name: AccG, kwargs: {k: 5, name: accg}}
      - {name: PrecK, kwargs: {k: 5, name: preck}}
      - {name: RecK, kwargs: {k: 5, name: reck}}
      - {name: F1K, kwargs: {k: 5, name: f1k}}

  optimizer: 
    name: AdamW
    kwargs: 
      lr: 0.00005    
  scheduler: 
    name: CosineAnnealingLR
    kwargs:
      T_max: 10

trainer:
  gpus: [1]
  min_epochs: 1
  max_epochs: 10
  num_processes: 1
  auto_select_gpus: False
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: False
  accumulate_grad_batches: 1
  precision: 16
  weights_summary: top
  auto_lr_find: False
  auto_scale_batch_size: False
  move_metrics_to_cpu: False
  wandb_logger:
    project: Logo_vienna_code_classification
    name: eb5_test

callback:
  callback_cls: LogoImageCallback
  num_samples: 8
  data_path: /home/ubuntu/datasets/LOGO/Logo_clf
  label_path: /home/ubuntu/datasets/LOGO/Logo_clf/meta.csv
  label_col: label
  gradcam: true