datamodule:
  dataset:
    label_path: /home/ubuntu/datasets/LOGO/Logo_clf/meta.csv
    augmentations: 
      - null
    transforms:
      - transforms.Resize((416, 416))
      - transforms.ToTensor()
      - transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
  dataloader:
    num_workers: 4
    batch_size: 16

lightning_module:
  model:
    name: efficientnet_b5_pretrained
    kwargs:
      num_classes: 392
    ckpt: /home/ubuntu/yha/AutoTrainer/autotrainer/working/logo_project/logo_clf/b5/test/results/train/ckpt/epoch=004-avg_val_loss=0.9735.ckpt
  evaluation:
    items:
      - {name: AccS, kwargs: {k: 1}}
      - {name: AccG, kwargs: {k: 1}}
      - {name: PrecK, kwargs: {k: 1}}
      - {name: RecK, kwargs: {k: 1}}
      - {name: F1K, kwargs: {k: 1}}

trainer:
  wandb_logger:
    project: Logo_vienna_code_classification
    name: test_eb5_cv0_epoch4_k1

callback:
  num_samples: 32
  data_path: /home/ubuntu/datasets/LOGO/Logo_clf
  label_path: /home/ubuntu/datasets/LOGO/Logo_clf/meta.csv
  label_col: label
  k: 1