datamodule:
  dataset:
    data_path: /home/ubuntu/datasets/LOGO/Logo_clf
    label_path: /home/ubuntu/datasets/LOGO/Logo_clf/meta_mini_3.csv
    augmentations: 
      - transforms.RandomHorizontalFlip(p=1)
      - transforms.RandomVerticalFlip(p=1)
      - transforms.CenterCrop((300, 300))
      - transforms.Pad((100, 100), padding_mode="edge")
      - transforms.AutoAugment()
    transforms:
      - transforms.Resize((416, 416))
      - transforms.RandomGrayscale(p=0.2)
      - transforms.RandomInvert(p=0.2)
      - transforms.ToTensor()
      - transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    num_classes: 3
    random_split: False
  dataloader:
    num_workers: 2
    batch_size: 4
    shuffle: True
    drop_last: False
  
lightning_module:
  model: 
    name: vit_b16_imagenet1k
    kwargs:
      num_classes: 3
      image_size: 416
    ckpt: null
  loss:
    name: torch.nn.CrossEntropyLoss
    kwargs: {}
  evaluation:
    items:
      - {name: torchmetrics.Accuracy, kwargs: {}}
  optimizer: 
    name: AdamW
    kwargs: 
      lr: 0.00005    
  scheduler: 
    name: CosineAnnealingLR
    kwargs:
      T_max: 10

trainer:
  gpus: [0]
  min_epochs: 1
  max_epochs: 10
  num_processes: 1
  auto_select_gpus: False
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: False
  accumulate_grad_batches: 1
  precision: 32
  weights_summary: top
  auto_lr_find: False
  auto_scale_batch_size: False
  move_metrics_to_cpu: False
  wandb_logger:
    project: Logo_vienna_code_classification
    name: initial

callback:
  callback_cls: LogoImageCallback
  num_samples: 8
  data_path: /home/ubuntu/datasets/LOGO/Logo_clf
  label_path: /home/ubuntu/datasets/LOGO/Logo_clf/meta.csv
  label_col: label
  gradcam: true
  k: 5